import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const imageUrl = "https://logowik.com/content/uploads/images/firebase.jpg";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300..900;1,300..900&display=swap"
          rel="stylesheet"
        />
      </head>

      <body className={inter.className}>
        <div className="bg-gray-950 h-screen flex flex-col gap-2" dir="rtl">
          <div className="bg-slate-900 w-full h-14 flex items-center gap-2 px-4">
            <img src={imageUrl} className="aspect-square h-10 rounded-full" />
            <div>ديمو المطاعم</div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
